require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TargetMonthsController do

  # This should return the minimal set of attributes required to create a valid
  # TargetMonth. As you add validations to TargetMonth, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "company_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TargetMonthsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all target_months as @target_months" do
      target_month = TargetMonth.create! valid_attributes
      get :index, {}, valid_session
      assigns(:target_months).should eq([target_month])
    end
  end

  describe "GET show" do
    it "assigns the requested target_month as @target_month" do
      target_month = TargetMonth.create! valid_attributes
      get :show, {:id => target_month.to_param}, valid_session
      assigns(:target_month).should eq(target_month)
    end
  end

  describe "GET new" do
    it "assigns a new target_month as @target_month" do
      get :new, {}, valid_session
      assigns(:target_month).should be_a_new(TargetMonth)
    end
  end

  describe "GET edit" do
    it "assigns the requested target_month as @target_month" do
      target_month = TargetMonth.create! valid_attributes
      get :edit, {:id => target_month.to_param}, valid_session
      assigns(:target_month).should eq(target_month)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TargetMonth" do
        expect {
          post :create, {:target_month => valid_attributes}, valid_session
        }.to change(TargetMonth, :count).by(1)
      end

      it "assigns a newly created target_month as @target_month" do
        post :create, {:target_month => valid_attributes}, valid_session
        assigns(:target_month).should be_a(TargetMonth)
        assigns(:target_month).should be_persisted
      end

      it "redirects to the created target_month" do
        post :create, {:target_month => valid_attributes}, valid_session
        response.should redirect_to(TargetMonth.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved target_month as @target_month" do
        # Trigger the behavior that occurs when invalid params are submitted
        TargetMonth.any_instance.stub(:save).and_return(false)
        post :create, {:target_month => { "company_id" => "invalid value" }}, valid_session
        assigns(:target_month).should be_a_new(TargetMonth)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TargetMonth.any_instance.stub(:save).and_return(false)
        post :create, {:target_month => { "company_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested target_month" do
        target_month = TargetMonth.create! valid_attributes
        # Assuming there are no other target_months in the database, this
        # specifies that the TargetMonth created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TargetMonth.any_instance.should_receive(:update).with({ "company_id" => "1" })
        put :update, {:id => target_month.to_param, :target_month => { "company_id" => "1" }}, valid_session
      end

      it "assigns the requested target_month as @target_month" do
        target_month = TargetMonth.create! valid_attributes
        put :update, {:id => target_month.to_param, :target_month => valid_attributes}, valid_session
        assigns(:target_month).should eq(target_month)
      end

      it "redirects to the target_month" do
        target_month = TargetMonth.create! valid_attributes
        put :update, {:id => target_month.to_param, :target_month => valid_attributes}, valid_session
        response.should redirect_to(target_month)
      end
    end

    describe "with invalid params" do
      it "assigns the target_month as @target_month" do
        target_month = TargetMonth.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TargetMonth.any_instance.stub(:save).and_return(false)
        put :update, {:id => target_month.to_param, :target_month => { "company_id" => "invalid value" }}, valid_session
        assigns(:target_month).should eq(target_month)
      end

      it "re-renders the 'edit' template" do
        target_month = TargetMonth.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TargetMonth.any_instance.stub(:save).and_return(false)
        put :update, {:id => target_month.to_param, :target_month => { "company_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested target_month" do
      target_month = TargetMonth.create! valid_attributes
      expect {
        delete :destroy, {:id => target_month.to_param}, valid_session
      }.to change(TargetMonth, :count).by(-1)
    end

    it "redirects to the target_months list" do
      target_month = TargetMonth.create! valid_attributes
      delete :destroy, {:id => target_month.to_param}, valid_session
      response.should redirect_to(target_months_url)
    end
  end

end
